export const GET_RANDOM_RECIPES = "GET_RANDOM_RECIPES"
export const GET_QUERIED_RECIPE = "GET_QUERIED_RECIPE"
export const SAVE_RECIPE = "SAVE_RECIPE"

export const GET_SAVED_RECIPE = "GET_SAVED_RECIPE"
export const CREATE_RECIPE = "CREATE_RECIPE"
export const DELETE_RECIPE = "DELETE_RECIPE"

export const CREATE_NOTE = "CREATE_NOTE"
export const DELETE_NOTE = "DELETE_NOTE"